import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Clock3, Cpu, Database, Server, Wrench } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { getLatestOutput, getRunHistory, getServiceStatus } from "../../shared/api/agentOutputApi";
import { formatNumber, formatWindow } from "../../shared/lib/format";
import { MetricCard } from "../../shared/ui/MetricCard";
import { ErrorState, LoadingState } from "../../shared/ui/PageState";
import { StatusBadge } from "../../shared/ui/StatusBadge";
import type { TimezoneMode } from "../../shared/model/types";

export function OperationsPage({ timezone }: { timezone: TimezoneMode }) {
  const historyQuery = useQuery({ queryKey: ["run-history"], queryFn: getRunHistory });
  const latestQuery = useQuery({ queryKey: ["latest-output"], queryFn: getLatestOutput });
  const statusQuery = useQuery({ queryKey: ["result-service-status"], queryFn: getServiceStatus });
  if (historyQuery.isLoading || latestQuery.isLoading || statusQuery.isLoading) return <LoadingState />;
  if (historyQuery.error || latestQuery.error || statusQuery.error) return <ErrorState message={(historyQuery.error ?? latestQuery.error ?? statusQuery.error)?.message ?? "운영 상태를 불러오지 못했습니다."} />;
  const runHistory = historyQuery.data ?? [];
  const service = statusQuery.data!;
  const failed = runHistory.filter((run) => run.status === "partial").length;
  const successful = runHistory.filter((run) => run.status !== "partial").length;
  const successRate = runHistory.length ? Math.round((successful / runHistory.length) * 100) : 0;
  const averageLatency = runHistory.length ? Math.round(runHistory.reduce((sum, run) => sum + run.latency_seconds, 0) / runHistory.length) : 0;
  const tokenData = runHistory.map((run) => ({ label: new Intl.DateTimeFormat("ko-KR", { timeZone: timezone === "KST" ? "Asia/Seoul" : "UTC", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(run.window.end)), input: run.usage.input_tokens, output: run.usage.output_tokens }));
  const latestPartial = [...runHistory].reverse().find((run) => run.status === "partial");
  return <div className="page-stack">
    <section className="page-heading"><div><span className="eyebrow">SYSTEM RELIABILITY</span><h2>위협 상태와 시스템 장애를 분리합니다</h2><p>판정이 없는 이유가 안전 때문인지 에이전트 실패 때문인지 운영 지표로 확인합니다.</p></div><div className="page-heading__stat page-heading__stat--success"><CheckCircle2 size={18} /><span>실행 성공률</span><strong>{successRate}%</strong></div></section>
    <section className="metric-grid"><MetricCard label="정상 실행" value={successful} hint={`파일 ${runHistory.length}개 검증`} icon={<CheckCircle2 size={18} />} tone="success" /><MetricCard label="부분 실패" value={failed} hint="안전 상태로 집계 금지" icon={<AlertTriangle size={18} />} tone="danger" /><MetricCard label="평균 탐지 지연" value={`${averageLatency}초`} hint="window.end부터 결과 생성까지" icon={<Clock3 size={18} />} /><MetricCard label="도구 로딩 오류" value={service.import_errors.length} hint={service.import_errors.length ? "agent_trace 확인 필요" : "import_errors 비어 있음"} icon={<Wrench size={18} />} tone={service.import_errors.length ? "danger" : "success"} /></section>
    <section className="dashboard-grid dashboard-grid--wide"><article className="panel chart-panel"><div className="panel__header"><div><span className="eyebrow">TOKEN USAGE</span><h2>실행별 모델 사용량</h2></div><Cpu size={18} /></div><div className="chart-legend"><span><i className="legend-dot legend-dot--observed" />입력 토큰</span><span><i className="legend-dot legend-dot--undetermined" />출력 토큰</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={tokenData} margin={{ left: -8, right: 8 }}><CartesianGrid vertical={false} stroke="#1b3038" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#718792", fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#718792", fontSize: 11 }} /><Tooltip formatter={(value) => formatNumber(Number(value))} contentStyle={{ background: "#0c181e", border: "1px solid #213942", borderRadius: 8 }} /><Bar dataKey="input" stackId="a" fill="#29d3c2" /><Bar dataKey="output" stackId="a" fill="#f4b84a" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></article><article className="panel health-panel"><div className="panel__header"><div><span className="eyebrow">RESULT PIPELINE</span><h2>결과 수집 상태</h2></div><Server size={18} /></div><ul className="health-list"><li><span className="health-dot health-dot--ok" /><div><strong>결과 폴더 감시</strong><small>{service.output_directory}</small></div><b>활성</b></li><li><span className={service.parse_errors.length ? "health-dot health-dot--warning" : "health-dot health-dot--ok"} /><div><strong>JSON 구조 검증</strong><small>{service.parse_errors.length ? `${service.parse_errors.length}개 파일 격리` : `${service.parsed_output_count}개 파일 정상`}</small></div><b>{service.parse_errors.length ? "주의" : "정상"}</b></li><li><span className="health-dot health-dot--ok" /><div><strong>임시 파일 제외</strong><small>.json.tmp {service.ignored_temporary_file_count}개 무시 중</small></div><b>정상</b></li><li><span className={failed ? "health-dot health-dot--warning" : "health-dot health-dot--ok"} /><div><strong>실행 연속성</strong><small>최근 {runHistory.length}회 중 부분 실패 {failed}회</small></div><b>{failed ? "주의" : "정상"}</b></li></ul></article></section>
    {latestPartial ? <section className="panel incident-panel"><div className="incident-panel__icon"><AlertTriangle size={19} /></div><div><span className="eyebrow">RECENT FAILURE</span><h2>부분 실패 실행</h2><p>{latestQuery.data?.detection.run_id === latestPartial.run_id ? latestQuery.data.detection.summary : "감지를 완료하지 못했습니다. 이 구간의 판정 0건은 안전을 의미하지 않습니다."}</p></div><div className="incident-panel__meta"><StatusBadge status="partial" /><span>{formatWindow(latestPartial.window.start, latestPartial.window.end, timezone)}</span><code>{latestPartial.run_id}</code></div></section> : null}
    <section className="panel"><div className="panel__header"><div><span className="eyebrow">DATA CONTRACT</span><h2>데이터 무결성 점검</h2></div><Database size={18} /></div><div className="contract-grid"><div><CheckCircle2 size={17} /><span><strong>.json.tmp 제외</strong><small>{service.ignored_temporary_file_count}개 임시 파일 제외</small></span></div><div><CheckCircle2 size={17} /><span><strong>배열·필드 관계 검사</strong><small>상태별 필수 조건과 부분집합 검증</small></span></div><div><CheckCircle2 size={17} /><span><strong>동적 필드 대응</strong><small>알 수 없는 threat/evidence type 허용</small></span></div><div className={service.parse_errors.length ? "contract-grid__error" : ""}>{service.parse_errors.length ? <AlertTriangle size={17} /> : <CheckCircle2 size={17} />}<span><strong>파싱 오류 격리</strong><small>{service.parse_errors.length ? `${service.parse_errors.length}개 파일 격리됨` : "오류 파일 없음"}</small></span></div></div></section>
  </div>;
}
